#ifndef PROTOCOL_H
#define PROTOCOL_H
typedef  unsigned int uint;
enum ENUM_MSG_TYPE
{
    ENUM_MSG_ADDFRIEND_REQUEST,
    ENUM_MSG_ADDFRIEND_RESPEND,
    ENUM_MSG_ONLINEUSER_REQUEST,
    ENUM_MSG_ONLINEUSER_RESPEND,
    ENUM_MSG_FINDUSER_REQUEST,
    ENUM_MSG_FINDUSER_RESPEND,
    ENUM_MSG_REGIST_REQUEST,
    ENUM_MSG_REGIST_RESPEND,
    ENUM_MSG_LOGIN_REQUEST,
    ENUM_MSG_LOGIN_RESPEND,
    ENUM_MSG_TYPE_REQUEST,
    ENUM_MSG_TYPE_RESPENDD,
    ENUM_MSG_ADDFRIEND_AGREE_REQUEST,
    ENUM_MSG_ADDFRIEND_AGREE_RESPEND,
    ENUM_MSG_FLUSHFRIEND_AGREE_REQUEST,
    ENUM_MSG_FLUSHFRIEND_AGREE_RESPEND,
    ENUM_MSG_DELFRIEND_REQUEST,
    ENUM_MSG_DELFRIEND_RESPEND,
    ENUM_MSG_CHATFRIEND_REQUEST,
    ENUM_MSG_CHATFRIEND_RESPEND,
    ENUM_MSG_MKDIRFILE_REQUEST,
    ENUM_MSG_MKDIRFILE_RESPEND,
    ENUM_MSG_FLUSHFILE_REQUEST,
    ENUM_MSG_FLUSHFILE_RESPEND,
    ENUM_MSG_DELFILE_REQUEST,
    ENUM_MSG_DELFILE_RESPEND,
    ENUM_MSG_DELDIR_REQUEST,
    ENUM_MSG_DELDIR_RESPEND,
    ENUM_MSG_RENAMEFILE_REQUEST,
    ENUM_MSG_RENAMEFILE_RESPEND,
    ENUM_MSG_MOVEFILE_REQUEST,
    ENUM_MSG_MOVEFILE_RESPEND,
    ENUM_MSG_UPLOADFILE_REQUEST,
    ENUM_MSG_UPLOADFILE_RESPEND,
    ENUM_MSG_UPLOADFILE_DATA_REQUEST,
    ENUM_MSG_UPLOADFILE_DATA_RESPEND,
    ENUM_MSG_SHAREFILE_REQUEST,
    ENUM_MSG_SHAREFILE_RESPEND,
    ENUM_MSG_SHAREFILE_AGREE_REQUEST,
    ENUM_MSG_SHAREFILE_AGREE_RESPEND,
};

struct PDU{//协议数据单元结构体
    uint  uiPDUlen;//总的协议数据长度
    uint  uiMsglen;//实际消息的长度
    uint  uiMsgType;//消息类型
    char caData[64];//参数
    char caMsg[];//实际消息
};
struct FileInfo
{
    char name[32];
    int iFileType;
};

PDU *mkPDU(uint  uiMsglen);
#endif // PROTOCOL_H
